# coding: utf-8

"""
    Selectel DNS API

    Simple Selectel DNS API.

    OpenAPI spec version: 1.0.0
    Contact: info@mdsina.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import selectel_dns_api
from selectel_dns_api.rest import ApiException
from selectel_dns_api.apis.domains_api import DomainsApi


class TestDomainsApi(unittest.TestCase):
    """ DomainsApi unit test stubs """

    def setUp(self):
        self.api = selectel_dns_api.apis.domains_api.DomainsApi()

    def tearDown(self):
        pass

    def test_add_domain(self):
        """
        Test case for add_domain

        Create new domain
        """
        pass

    def test_delete_domain(self):
        """
        Test case for delete_domain

        Deletes a domain
        """
        pass

    def test_get_domain_by_id(self):
        """
        Test case for get_domain_by_id

        Find domain by ID
        """
        pass

    def test_get_domain_by_name(self):
        """
        Test case for get_domain_by_name

        Find domain by name
        """
        pass

    def test_get_domain_zone_file(self):
        """
        Test case for get_domain_zone_file

        Find domain by name
        """
        pass

    def test_get_domains(self):
        """
        Test case for get_domains

        Getting domains info
        """
        pass

    def test_update_domain(self):
        """
        Test case for update_domain

        Updates a domain
        """
        pass


if __name__ == '__main__':
    unittest.main()
