# coding: utf-8

"""
    Selectel DNS API

    Simple Selectel DNS API.

    OpenAPI spec version: 1.0.0
    Contact: info@mdsina.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import selectel_dns_api
from selectel_dns_api.rest import ApiException
from selectel_dns_api.models.domain import Domain


class TestDomain(unittest.TestCase):
    """ Domain unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomain(self):
        """
        Test Domain
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = selectel_dns_api.models.domain.Domain()
        pass


if __name__ == '__main__':
    unittest.main()
