# coding: utf-8

"""
    Selectel DNS API

    Simple Selectel DNS API.

    OpenAPI spec version: 1.0.0
    Contact: info@mdsina.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import selectel_dns_api
from selectel_dns_api.rest import ApiException
from selectel_dns_api.apis.ptr_api import PtrApi


class TestPtrApi(unittest.TestCase):
    """ PtrApi unit test stubs """

    def setUp(self):
        self.api = selectel_dns_api.apis.ptr_api.PtrApi()

    def tearDown(self):
        pass

    def test_add_ptr_record(self):
        """
        Test case for add_ptr_record

        Create new PTR record
        """
        pass

    def test_delete_ptr_record(self):
        """
        Test case for delete_ptr_record

        Deletes a PTR record
        """
        pass

    def test_get_ptr_record_by_id(self):
        """
        Test case for get_ptr_record_by_id

        Find information about PTR record by ID
        """
        pass

    def test_get_ptr_records(self):
        """
        Test case for get_ptr_records

        Getting PTR records
        """
        pass

    def test_update_ptr_record(self):
        """
        Test case for update_ptr_record

        Updates a PTR record
        """
        pass


if __name__ == '__main__':
    unittest.main()
