# coding: utf-8

"""
    Selectel DNS API

    Simple Selectel DNS API.

    OpenAPI spec version: 1.0.0
    Contact: info@mdsina.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import selectel_dns_api
from selectel_dns_api.rest import ApiException
from selectel_dns_api.apis.tags_api import TagsApi


class TestTagsApi(unittest.TestCase):
    """ TagsApi unit test stubs """

    def setUp(self):
        self.api = selectel_dns_api.apis.tags_api.TagsApi()

    def tearDown(self):
        pass

    def test_add_new_tag(self):
        """
        Test case for add_new_tag

        Create new tag
        """
        pass

    def test_delete_tag(self):
        """
        Test case for delete_tag

        Deletes a tag
        """
        pass

    def test_get_tag_by_id(self):
        """
        Test case for get_tag_by_id

        Find information about tag by ID
        """
        pass

    def test_get_tags(self):
        """
        Test case for get_tags

        Getting tags
        """
        pass

    def test_update_tag(self):
        """
        Test case for update_tag

        Updates a tag
        """
        pass


if __name__ == '__main__':
    unittest.main()
