# coding: utf-8

"""
    Selectel DNS API

    Simple Selectel DNS API.

    OpenAPI spec version: 1.0.0
    Contact: info@mdsina.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import selectel_dns_api
from selectel_dns_api.rest import ApiException
from selectel_dns_api.apis.records_api import RecordsApi


class TestRecordsApi(unittest.TestCase):
    """ RecordsApi unit test stubs """

    def setUp(self):
        self.api = selectel_dns_api.apis.records_api.RecordsApi()

    def tearDown(self):
        pass

    def test_add_resource_record(self):
        """
        Test case for add_resource_record

        Create resource records for domain
        """
        pass

    def test_batch_update_resources_records(self):
        """
        Test case for batch_update_resources_records

        Mass update of domain's resources records
        """
        pass

    def test_delete_resource_record(self):
        """
        Test case for delete_resource_record

        Deletes a resource record
        """
        pass

    def test_get_resource_records_by_domain_id(self):
        """
        Test case for get_resource_records_by_domain_id

        Getting records info
        """
        pass

    def test_get_resource_records_by_domain_name(self):
        """
        Test case for get_resource_records_by_domain_name

        Find resource records info for domain by name
        """
        pass

    def test_update_resource_record(self):
        """
        Test case for update_resource_record

        Updates a resource record
        """
        pass


if __name__ == '__main__':
    unittest.main()
