# coding: utf-8

"""
    Selectel DNS API

    Simple Selectel DNS API.

    OpenAPI spec version: 1.0.0
    Contact: info@mdsina.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import selectel_dns
from selectel_dns.rest import ApiException
from selectel_dns.apis.ptr_api import PtrApi


class TestPtrApi(unittest.TestCase):
    """ PtrApi unit test stubs """

    def setUp(self):
        self.api = selectel_dns.apis.ptr_api.PtrApi()

    def tearDown(self):
        pass

    def test_add_ptr_record(self):
        """
        Test case for add_ptr_record

        Create new PTR record
        """
        pass

    def test_delete_ptr_record(self):
        """
        Test case for delete_ptr_record

        Deletes a PTR record
        """
        pass

    def test_get_ptr_record_by_id(self):
        """
        Test case for get_ptr_record_by_id

        Find information about PTR record by ID
        """
        pass

    def test_get_ptr_records(self):
        """
        Test case for get_ptr_records

        Getting PTR records
        """
        pass

    def test_update_ptr_record(self):
        """
        Test case for update_ptr_record

        Updates a PTR record
        """
        pass


if __name__ == '__main__':
    unittest.main()
