# coding: utf-8

"""
    Selectel DNS API

    Simple Selectel DNS API.

    OpenAPI spec version: 1.0.1
    Contact: info@mdsina.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .api_response import ApiResponse
from .batch_update_model import BatchUpdateModel
from .domain import Domain
from .new_domain import NewDomain
from .new_or_updated_ptr_record import NewOrUpdatedPTRRecord
from .new_or_updated_record import NewOrUpdatedRecord
from .new_or_updated_tag import NewOrUpdatedTag
from .ptr_record import PTRRecord
from .record import Record
from .tag import Tag
from .updated_domain import UpdatedDomain
