# coding: utf-8

"""
    Selectel DNS API

    Simple Selectel DNS API.

    OpenAPI spec version: 1.0.0
    Contact: info@mdsina.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class NewDomain(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'bind_zone': 'str'
    }

    attribute_map = {
        'name': 'name',
        'bind_zone': 'bind_zone'
    }

    def __init__(self, name=None, bind_zone=None):
        """
        NewDomain - a model defined in Swagger
        """

        self._name = None
        self._bind_zone = None

        self.name = name
        if bind_zone is not None:
          self.bind_zone = bind_zone

    @property
    def name(self):
        """
        Gets the name of this NewDomain.

        :return: The name of this NewDomain.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this NewDomain.

        :param name: The name of this NewDomain.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def bind_zone(self):
        """
        Gets the bind_zone of this NewDomain.
        DNS Zone in BIND format

        :return: The bind_zone of this NewDomain.
        :rtype: str
        """
        return self._bind_zone

    @bind_zone.setter
    def bind_zone(self, bind_zone):
        """
        Sets the bind_zone of this NewDomain.
        DNS Zone in BIND format

        :param bind_zone: The bind_zone of this NewDomain.
        :type: str
        """

        self._bind_zone = bind_zone

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, NewDomain):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
