# coding: utf-8

"""
    Selectel DNS API

    Simple Selectel DNS API.

    OpenAPI spec version: 1.0.0
    Contact: info@mdsina.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PTRRecord(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'ip': 'str',
        'content': 'str',
        'user_id': 'int'
    }

    attribute_map = {
        'id': 'id',
        'ip': 'ip',
        'content': 'content',
        'user_id': 'user_id'
    }

    def __init__(self, id=None, ip=None, content=None, user_id=None):
        """
        PTRRecord - a model defined in Swagger
        """

        self._id = None
        self._ip = None
        self._content = None
        self._user_id = None

        if id is not None:
          self.id = id
        if ip is not None:
          self.ip = ip
        if content is not None:
          self.content = content
        if user_id is not None:
          self.user_id = user_id

    @property
    def id(self):
        """
        Gets the id of this PTRRecord.
        PTR record identifier

        :return: The id of this PTRRecord.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this PTRRecord.
        PTR record identifier

        :param id: The id of this PTRRecord.
        :type: int
        """

        self._id = id

    @property
    def ip(self):
        """
        Gets the ip of this PTRRecord.

        :return: The ip of this PTRRecord.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """
        Sets the ip of this PTRRecord.

        :param ip: The ip of this PTRRecord.
        :type: str
        """

        self._ip = ip

    @property
    def content(self):
        """
        Gets the content of this PTRRecord.
        Domain name

        :return: The content of this PTRRecord.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """
        Sets the content of this PTRRecord.
        Domain name

        :param content: The content of this PTRRecord.
        :type: str
        """

        self._content = content

    @property
    def user_id(self):
        """
        Gets the user_id of this PTRRecord.

        :return: The user_id of this PTRRecord.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """
        Sets the user_id of this PTRRecord.

        :param user_id: The user_id of this PTRRecord.
        :type: int
        """

        self._user_id = user_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PTRRecord):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
