# coding: utf-8

"""
    Selectel DNS API

    Simple Selectel DNS API.

    OpenAPI spec version: 1.0.0
    Contact: info@mdsina.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Tag(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'domains': 'list[int]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'domains': 'domains'
    }

    def __init__(self, id=None, name=None, domains=None):
        """
        Tag - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._domains = None

        if id is not None:
          self.id = id
        if name is not None:
          self.name = name
        if domains is not None:
          self.domains = domains

    @property
    def id(self):
        """
        Gets the id of this Tag.

        :return: The id of this Tag.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Tag.

        :param id: The id of this Tag.
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this Tag.

        :return: The name of this Tag.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Tag.

        :param name: The name of this Tag.
        :type: str
        """

        self._name = name

    @property
    def domains(self):
        """
        Gets the domains of this Tag.

        :return: The domains of this Tag.
        :rtype: list[int]
        """
        return self._domains

    @domains.setter
    def domains(self, domains):
        """
        Sets the domains of this Tag.

        :param domains: The domains of this Tag.
        :type: list[int]
        """

        self._domains = domains

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Tag):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
